export const cardsData = {
	vegetables: [
		{
			id: 0,
			cardName: "cabbage",
			cardNameRu: "капуста",
			img: "./assets/Vegetables/cabbage.jpg",
			audio: "./assets/pronounciation/cabbage.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 1,
			cardName: "carrot",
			cardNameRu: "морковка",
			img: "./assets/Vegetables/carrot.jpg",
			audio: "./assets/pronounciation/carrot.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 2,
			cardName: "cucumber",
			cardNameRu: "огурец",
			img: "./assets/Vegetables/cucumber.jpg",
			audio: "./assets/pronounciation/cucumber.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 3,
			cardName: "onion",
			cardNameRu: "лук",
			img: "./assets/Vegetables/onion.jpg",
			audio: "./assets/pronounciation/onion.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 4,
			cardName: "pepper",
			cardNameRu: "перец",
			img: "./assets/Vegetables/pepper.jpg",
			audio: "./assets/pronounciation/pepper.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 5,
			cardName: "tomato",
			cardNameRu: "помидор",
			img: "./assets/Vegetables/tomato.jpg",
			audio: "./assets/pronounciation/tomato.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 6,
			cardName: "zucchini",
			cardNameRu: "цукини",
			img: "./assets/Vegetables/zucchini.jpg",
			audio: "./assets/pronounciation/zucchini.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 7,
			cardName: "potato",
			cardNameRu: "картофель",
			img: "./assets/Vegetables/potato.jpg",
			audio: "./assets/pronounciation/potato.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
	],

	//   -----------------------------FRUITS
	fruits: [
		{
			id: 8,
			cardName: "apple",
			cardNameRu: "яблоко",
			img: "./assets/Fruits/apple.jpg",
			audio: "./assets/pronounciation/apple.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 9,
			cardName: "banana",
			cardNameRu: "банан",
			img: "./assets/Fruits/banana.jpg",
			audio: "./assets/pronounciation/banana.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 10,
			cardName: "grapes",
			cardNameRu: "виноград",
			img: "./assets/Fruits/grapes.jpg",
			audio: "./assets/pronounciation/grapes.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 11,
			cardName: "lemon",
			cardNameRu: "лимон",
			img: "./assets/Fruits/lemon.jpg",
			audio: "./assets/pronounciation/lemon.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 12,
			cardName: "orange",
			cardNameRu: "апельсин",
			img: "./assets/Fruits/orange.jpg",
			audio: "./assets/pronounciation/orange.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 13,
			cardName: "peach",
			cardNameRu: "персик",
			img: "./assets/Fruits/peach.jpg",
			audio: "./assets/pronounciation/peach.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 14,
			cardName: "pear",
			cardNameRu: "груша",
			img: "./assets/Fruits/pear.jpg",
			audio: "./assets/pronounciation/pear.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 15,
			cardName: "pineapple",
			cardNameRu: "ананас",
			img: "./assets/Fruits/pineapple.jpg",
			audio: "./assets/pronounciation/pineapple.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
	],

	//   -----------------------------HOME_ANIMALS
	"home animals": [
		{
			id: 16,
			cardName: "donkey",
			cardNameRu: "осёл",
			img: "./assets/Home_animals/donkey.jpg",
			audio: "./assets/pronounciation/donkey.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 17,
			cardName: "cat",
			cardNameRu: "кошка",
			img: "./assets/Home_animals/cat.jpg",
			audio: "./assets/pronounciation/cat.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 18,
			cardName: "cow",
			cardNameRu: "корова",
			img: "./assets/Home_animals/cow.jpg",
			audio: "./assets/pronounciation/cow.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 19,
			cardName: "goat",
			cardNameRu: "коза",
			img: "./assets/Home_animals/goat.jpg",
			audio: "./assets/pronounciation/goat.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 20,
			cardName: "rabbit",
			cardNameRu: "кролик",
			img: "./assets/Home_animals/rabbit.jpg",
			audio: "./assets/pronounciation/rabbit.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 21,
			cardName: "pig",
			cardNameRu: "свинья",
			img: "./assets/Home_animals/pig.jpg",
			audio: "./assets/pronounciation/pig.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 22,
			cardName: "sheep",
			cardNameRu: "овца",
			img: "./assets/Home_animals/sheep.jpg",
			audio: "./assets/pronounciation/sheep.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 23,
			cardName: "horse",
			cardNameRu: "лошадь",
			img: "./assets/Home_animals/horse.jpg",
			audio: "./assets/pronounciation/horse.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
	],

	"wild animals": [
		{
			id: 24,
			cardName: "bear",
			cardNameRu: "медведь",
			img: "./assets/Wild_animals/bear.jpg",
			audio: "./assets/pronounciation/bear.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 25,
			cardName: "monkey",
			cardNameRu: "обезьяна",
			img: "./assets/Wild_animals/monkey.jpg",
			audio: "./assets/pronounciation/monkey.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 26,
			cardName: "tiger",
			cardNameRu: "тигр",
			img: "./assets/Wild_animals/tiger.jpg",
			audio: "./assets/pronounciation/tiger.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 27,
			cardName: "lion",
			cardNameRu: "лев",
			img: "./assets/Wild_animals/lion.jpg",
			audio: "./assets/pronounciation/lion.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 28,
			cardName: "hippo",
			cardNameRu: "бегемот",
			img: "./assets/Wild_animals/hippo.jpg",
			audio: "./assets/pronounciation/hippo.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 29,
			cardName: "fox",
			cardNameRu: "лиса",
			img: "./assets/Wild_animals/fox.jpg",
			audio: "./assets/pronounciation/fox.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 30,
			cardName: "elephant",
			cardNameRu: "слон",
			img: "./assets/Wild_animals/elephant.jpg",
			audio: "./assets/pronounciation/elephant.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 31,
			cardName: "crocodile",
			cardNameRu: "крокодил",
			img: "./assets/Wild_animals/crocodile.jpg",
			audio: "./assets/pronounciation/crocodile.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
	],
	//      -----------------------------CLOTHES
	clothes: [
		{
			id: 32,
			cardName: "coat",
			cardNameRu: "пальто",
			img: "./assets/Clothes/coat.jpg",
			audio: "./assets/pronounciation/coat.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 33,
			cardName: "dress",
			cardNameRu: "платье",
			img: "./assets/Clothes/dress.jpg",
			audio: "./assets/pronounciation/dress.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 34,
			cardName: "hat",
			cardNameRu: "шляпа",
			img: "./assets/Clothes/hat.jpg",
			audio: "./assets/pronounciation/hat.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 35,
			cardName: "jeans",
			cardNameRu: "джинсы",
			img: "./assets/Clothes/jeans.jpg",
			audio: "./assets/pronounciation/jeans.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 36,
			cardName: "shirt",
			cardNameRu: "рубашка",
			img: "./assets/Clothes/shirt.jpg",
			audio: "./assets/pronounciation/shirt.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 37,
			cardName: "skirt",
			cardNameRu: "юбка",
			img: "./assets/Clothes/skirt.jpg",
			audio: "./assets/pronounciation/skirt.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 38,

			cardName: "socks",
			cardNameRu: "носки",
			img: "./assets/Clothes/socks.jpg",
			audio: "./assets/pronounciation/socks.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 39,
			cardName: "t-shirt",
			cardNameRu: "футболка",
			img: "./assets/Clothes/t-shirt.jpg",
			audio: "./assets/pronounciation/socks.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
	],
	// //  -------------------WEATHER
	weather: [
		{
			id: 40,
			cardName: "cloud",
			cardNameRu: "облако",
			img: "./assets/Weather/cloud.jpg",
			audio: "./assets/pronounciation/cloud.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 41,
			cardName: "fog",
			cardNameRu: "туман",
			img: "./assets/Weather/fog.jpg",
			audio: "./assets/pronounciation/fog.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 42,
			cardName: "lightening",
			cardNameRu: "молния",
			img: "./assets/Weather/lightening.jpg",
			audio: "./assets/pronounciation/lightening.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 43,
			cardName: "rain",
			cardNameRu: "дождь",
			img: "./assets/Weather/rain.jpg",
			audio: "./assets/pronounciation/rain.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 44,
			cardName: "rainbow",
			cardNameRu: "радуга",
			img: "./assets/Weather/rainbow.jpg",
			audio: "./assets/pronounciation/rainbow.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 45,
			cardName: "snow",
			cardNameRu: "снег",
			img: "./assets/Weather/snow.jpg",
			audio: "./assets/pronounciation/snow.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 46,
			cardName: "sun",
			cardNameRu: "солнце",
			img: "./assets/Weather/sun.jpg",
			audio: "./assets/pronounciation/sun.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 47,
			cardName: "wind",
			cardNameRu: "дождь",
			img: "./assets/Weather/wind.jpg",
			audio: "./assets/pronounciation/wind.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
	],
	// // ----------------------PROFESSIONS
	professions: [
		{
			id: 48,
			cardName: "cook",
			cardNameRu: "повар",
			img: "./assets/Professions/cook.jpg",
			audio: "./assets/pronounciation/cook.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 49,
			cardName: "doctor",
			cardNameRu: "доктор",
			img: "./assets/Professions/doctor.jpg",
			audio: "./assets/pronounciation/doctor.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 50,
			cardName: "engineer",
			cardNameRu: "инженер",
			img: "./assets/Professions/engineer.jpg",
			audio: "./assets/pronounciation/engineer.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 51,
			cardName: "fireman",
			cardNameRu: "пожарный",
			img: "./assets/Professions/fireman.jpg",
			audio: "./assets/pronounciation/fireman.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 52,
			cardName: "hairdresser",
			cardNameRu: "парикмахер",
			img: "./assets/Professions/hairdresser.jpg",
			audio: "./assets/pronounciation/hairdresser.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 53,
			cardName: "police officer",
			cardNameRu: "полицейский",
			img: "./assets/Professions/police_officer.jpg",
			audio: "./assets/pronounciation/police_officer.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 54,
			cardName: "programmer",
			cardNameRu: "программист",
			img: "./assets/Professions/programmer.jpg",
			audio: "./assets/pronounciation/programmer.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 55,
			cardName: "teacher",
			cardNameRu: "учитель",
			img: "./assets/Professions/teacher.jpg",
			audio: "./assets/pronounciation/teacher.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
	],
	// // ------------------FOOD
	food: [
		{
			id: 56,
			cardName: "cake",
			cardNameRu: "торт",
			img: "./assets/Food/cake.jpg",
			audio: "./assets/pronounciation/cake.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 57,
			cardName: "eggs",
			cardNameRu: "яйца",
			img: "./assets/Food/eggs.jpg",
			audio: "./assets/pronounciation/eggs.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 58,
			cardName: "hamburger",
			cardNameRu: "гамбургер",
			img: "./assets/Food/hamburger.jpg",
			audio: "./assets/pronounciation/hamburger.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 59,
			cardName: "pasta",
			cardNameRu: "паста",
			img: "./assets/Food/pasta.jpg",
			audio: "./assets/pronounciation/pasta.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 60,
			cardName: "pizza",
			cardNameRu: "пицца",
			img: "./assets/Food/pizza.jpg",
			audio: "./assets/pronounciation/pizza.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 61,
			cardName: "porridge",
			cardNameRu: "каша",
			img: "./assets/Food/porridge.jpg",
			audio: "./assets/pronounciation/porridge.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 62,
			cardName: "salad",
			cardNameRu: "салат",
			img: "./assets/Food/salad.jpg",
			audio: "./assets/pronounciation/salad.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
		{
			id: 63,
			cardName: "soup",
			cardNameRu: "суп",
			img: "./assets/Food/soup.jpg",
			audio: "./assets/pronounciation/soup.mp3",
			attempts: 0,
			correct: 0,
			incorrect: 0,
		},
	],
};

export const categoryData = {
	"home animals": {
		cardName: "HOME ANIMALS",
		cardNameRu: "ДОМАШНИЕ ЖИВОТНЫЕ",
		img: "./assets/categories/animals_home.jpg",
	},
	"wild animals": {
		cardName: "WILD ANIMALS",
		cardNameRu: "ДИКИЕ ЖИВОТНЫЕ",
		img: "./assets/categories/animals_wild.jpg",
	},
	fruits: {
		cardName: "FRUITS",
		cardNameRu: "ФРУКТЫ",
		img: "./assets/categories/fruits.jpg",
	},
	vegetables: {
		cardName: "VEGETABLES",
		cardNameRu: "ОВОЩИ",
		img: "./assets/categories/vegetables.jpg",
	},
	clothes: {
		cardName: "CLOTHES",
		cardNameRu: "ОДЕЖДА",
		img: "./assets/categories/clothes.jpg",
	},
	food: {
		cardName: "FOOD",
		cardNameRu: "ЕДА",
		img: "./assets/categories/food.jpg",
	},
	professions: {
		cardName: "PROFESSIONS",
		cardNameRu: "ПРОФЕССИИ",
		img: "./assets/categories/professions.jpg",
	},
	weather: {
		cardName: "WEATHER",
		cardNameRu: "ПОГОДА",
		img: "./assets/categories/weather.jpg",
	},
};
